#!/usr/bin/env bash
# Configure /etc/hosts to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sed 's/^127.0.0.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts
sed -i '/facebook.com/d' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
rm /tmp/hosts
